# Generated by Django 3.0.7 on 2021-03-21 13:21

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import kitchens.models


class Migration(migrations.Migration):

    initial = True

    state_operations = [
        migrations.CreateModel(
            name='KitchenDecor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kitchen decor name')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=kitchens.models.Decor.kitchen_decor_directory_path)),
            ],
            options={
                'db_table': 'kitchens_kitchendecor',
                'verbose_name': 'Kithcen decor',
                'verbose_name_plural': 'Kitchen decors',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='KitchenExclusiveColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kitchen exclusive name')),
                ('color_hex', models.CharField(max_length=7, unique=True, verbose_name='Color code')),
            ],
            options={
                'db_table': 'kitchens_kitchenexclusivecolor',
                'verbose_name': 'Kithcen exclusive color',
                'verbose_name_plural': 'Kitchen exclusives colors',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='KitchenLaminateColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kitchen laminate name')),
                ('color_hex', models.CharField(max_length=7, unique=True, verbose_name='Color code')),
            ],
            options={
                'db_table': 'kitchens_kitchenlaminatecolor',
                'verbose_name': 'Kithcen laminate color',
                'verbose_name_plural': 'Kitchen laminates colors',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='KitchenPlywood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kitchen decor name')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=kitchens.models.Plywood.kitchen_plywood_directory_path)),
            ],
            options={
                'db_table': 'kitchens_kitchenplywood',
                'verbose_name': 'Kithcen plywood',
                'verbose_name_plural': 'Kitchen plywoods',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='KitchenSilkColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kitchen silk name')),
                ('color_hex', models.CharField(max_length=7, unique=True, verbose_name='Color code')),
            ],
            options={
                'db_table': 'kitchens_kitchensilkcolor',
                'verbose_name': 'Kithcen silk color',
                'verbose_name_plural': 'Kitchen silks colors',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='KitchenTrendColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kitchen trend name')),
                ('color_hex', models.CharField(max_length=7, unique=True, verbose_name='Color code')),
            ],
            options={
                'db_table': 'kitchens_kitchentrendcolor',
                'verbose_name': 'Kithcen trend color',
                'verbose_name_plural': 'Kitchen trend colors',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kitchen name')),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Hidden'), (3, 'Available'), (4, 'Discontinued')], default=1, verbose_name='Status')),
                ('slug', models.SlugField(help_text='A slug is a short label for something, containing only letters, numbers, underscores or hyphens. They’re generally used in URLs.', max_length=255, verbose_name='Slug')),
                ('thumbnail_description', models.CharField(max_length=255, verbose_name='Thumbnail description')),
                ('description', models.TextField(verbose_name='Description')),
                ('extra_description', models.TextField(blank=True, help_text='Will be displayed bellow pricing example', null=True, verbose_name='Extra description')),
                ('example_from_price', models.FloatField(blank=True, null=True, verbose_name='From price')),
                ('can_be_painted', models.BooleanField(default=False, help_text='Designates whether the product can be painted in suppliers 2000 colors', verbose_name='Can be painted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('image', models.ImageField(blank=True, help_text='Image must be above 3072x940px', null=True, upload_to=kitchens.models.Kitchen.kitchen_directory_path, verbose_name='Image')),
                ('decor_variants', models.ManyToManyField(blank=True, related_name='kitchen_decor', to='kitchens.KitchenDecor')),
                ('exclusive_variants', models.ManyToManyField(blank=True, related_name='kitchen_exclusive', to='kitchens.KitchenExclusiveColor')),
                ('laminate_variants', models.ManyToManyField(blank=True, related_name='kitchen_decor', to='kitchens.KitchenLaminateColor')),
                ('plywood_variants', models.ManyToManyField(blank=True, related_name='kitchen_plywood', to='kitchens.KitchenPlywood')),
                ('silk_variants', models.ManyToManyField(blank=True, related_name='kitchen_silk', to='kitchens.KitchenSilkColor')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='inventory.Supplier')),
                ('trend_variants', models.ManyToManyField(blank=True, related_name='kitchen_decor', to='kitchens.KitchenTrendColor')),
            ],
            options={
                'db_table': 'kitchens_kitchen',
                'verbose_name': 'Kitchen',
                'verbose_name_plural': 'Kitchens',
            },
            bases=(models.Model,),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
