# Generated by Django 3.0.7 on 2021-03-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kitchen',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kitchendecor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kitchenexclusivecolor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kitchenlaminatecolor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kitchenplywood',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kitchensilkcolor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kitchentrendcolor',
            table=None,
        ),
    ]
