# Generated by Django 3.0.7 on 2021-03-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0002_auto_20210324_2355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KitchenDecor',
            new_name='Decor',
        ),
        migrations.RenameModel(
            old_name='KitchenExclusiveColor',
            new_name='ExclusiveColor',
        ),
        migrations.RenameModel(
            old_name='KitchenLaminateColor',
            new_name='LaminateColor',
        ),
        migrations.RenameModel(
            old_name='KitchenPlywood',
            new_name='Plywood',
        ),
        migrations.RenameModel(
            old_name='KitchenSilkColor',
            new_name='SilkColor',
        ),
        migrations.RenameModel(
            old_name='KitchenTrendColor',
            new_name='TrendColor',
        ),
        migrations.AlterModelOptions(
            name='decor',
            options={'verbose_name': 'Decor', 'verbose_name_plural': 'Decors'},
        ),
        migrations.AlterModelOptions(
            name='exclusivecolor',
            options={'verbose_name': 'Exclusive color', 'verbose_name_plural': 'Exclusive colors'},
        ),
        migrations.AlterModelOptions(
            name='laminatecolor',
            options={'verbose_name': 'Laminate color', 'verbose_name_plural': 'Laminates colors'},
        ),
        migrations.AlterModelOptions(
            name='plywood',
            options={'verbose_name': 'Plywood', 'verbose_name_plural': 'Plywoods'},
        ),
        migrations.AlterModelOptions(
            name='silkcolor',
            options={'verbose_name': 'Silk color', 'verbose_name_plural': 'Silk colors'},
        ),
        migrations.AlterModelOptions(
            name='trendcolor',
            options={'verbose_name': 'Trend color', 'verbose_name_plural': 'Trend colors'},
        ),
    ]
