# Generated by Django 3.0.7 on 2021-05-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0003_auto_20210325_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='apply_filter',
            field=models.BooleanField(default=False, help_text='Apply filter to image if the image is light to maintain an acceptable contrast', verbose_name='Apply filter'),
        ),
    ]
