# Generated by Django 3.0.7 on 2021-10-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('kitchens', '0004_kitchen_apply_filter'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='suppliers.Supplier'),
        ),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=state_operations)]
