# Generated by Django 3.0.7 on 2021-02-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(choices=[('#F87171', 'Red'), ('#FBBF24', 'Yellow'), ('#34D399', 'Green'), ('#60A5FA', 'Blue'), ('#A78BFA', 'Purple'), ('#F472B6', 'Pink')], default='#F87171', max_length=8, verbose_name='avatar color'),
            preserve_default=False,
        ),
    ]
