# Generated by Django 3.0.7 on 2021-03-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2020-03-11', verbose_name='birth date'),
            preserve_default=False,
        ),
    ]
