# Generated by Django 3.0.7 on 2021-03-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210305_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('has_users_list', 'Can list users'), ('has_user_edit', 'Can edit a single user instance'), ('has_user_add', 'Can add a single user instance'), ('has_user_delete', 'Can delete a single user instance')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
