# Generated by Django 3.0.7 on 2021-10-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='supplier',
            managers=[
            ],
        ),
    ]
