# Generated by Django 4.0.4 on 2022-05-24 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_logs', '0003_rename_user_logentry_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='date_of_change',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
