name: "Setup project"
description: "Install dependencies and setup venv."
runs:
  using: "composite"
  steps:
    - name: "Set up Python"
      id: setup-python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.2

    - name: "Cache pip downloads"
      id: cache-pip-downloads
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          pip-${{ runner.os }}-

    - name: "Install poetry"
      shell: bash
      run: pip install poetry==1.1.10  poetry-core==1.0.6

    - name: "Cache Python venv"
      id: cache-venv
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('.python-version', 'poetry.lock') }}

    - name: Create and activate venv
      shell: bash
      run: |
        test -d "$GITHUB_WORKSPACE/.venv" || python -m venv "$GITHUB_WORKSPACE/.venv"
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      run: poetry install
      if: steps.cache-venv.outputs.cache-hit != 'true'