version: "3"

volumes:
  postgres:

services:
  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=aria
      - POSTGRES_PASSWORD=aria
      - POSTGRES_DB=aria
    command:
      # We do not need replication-level logging on dev setups
      - --wal_level=minimal
      - --max_wal_senders=0
      #  Double the default value to help index builds
      - --maintenance_work_mem=131072
    volumes:
        - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  redis:
    image: redis:7.0.1-alpine
    ports:
      - 6379:6379

  minio:
    image: quay.io/minio/minio
    ports:
      - '127.0.0.1:9000:9001'
#      - '127.0.0.1:9001:9001'
    environment:
      - MINIO_ACCESS_KEY=aria-dev
      - MINIO_SECRET_KEY=aria-dev
      - MINIO_ROOT_USER=aria
      - MINIO_ROOT_PASSWORD=ariatestpassword
    command: server /data --console-address ":9001"

  thumbor:
    image: minimalcompact/thumbor
    ports:
      - "127.0.0.1:10000:80"
    environment:
      SECURITY_KEY: 'aria-dev'
      MAX_WIDTH: 2048
      MAX_HEIGHT: 1150
      QUALITY: 98
      AUTO_WEBP: 'True'
      ALLOW_UNSAFE_URL: 1
      ALLOW_OLD_URLS: 0
#      LOADER: 'thumbor_aws.loaders.s3_loader'
#      STORAGE: 'thumbor_aws.storage'
#      RESULT_STORAGE: 'thumbor_aws.result_storage'

#      AWS_ACCESS_KEY_ID: 'aria-dev'
#      AWS_SECRET_ACCESS_KEY: 'aria-dev'

      # NEW
      AWS_LOADER_REGION_NAME: "eu-north-1"
      AWS_LOADER_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_LOADER_S3_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_LOADER_S3_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}


#      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}

    links:
      - minio

