[tool.poetry]
name = "aria-api"
version = "0.1.0"
description = ""
authors = ["danielkjellid <daniel.kjellid@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10.2"
appnope = "0.1.2"
backcall = "0.2.0"
certifi = "2021.10.8"
charset-normalizer = "2.0.10"
confusable_homoglyphs = "3.2.0"
decorator = "5.1.1"
dj-database-url = "0.5.0"
django-appconf = "1.0.5"
django-cors-headers = "3.11.0"
django-environ = "0.8.1"
django-extensions = "^3.1.5"
django-heroku = "0.3.1"
django-imagekit = "4.0.2"
django-s3-storage = "^0.13.5"
djangorestframework = "^3.13.1"
djangorestframework-simplejwt = "5.0.0"
docutils = "0.18.1"
gunicorn = "20.1.0"
idna = "3.3"
ipython = "8.0.1"
jedi = "0.18.1"
jmespath = "0.10.0"
matplotlib-inline = "0.1.3"
mypy = "0.931"
mypy-extensions = "0.4.3"
parso = "0.8.3"
pexpect = "4.8.0"
phonenumbers = "8.12.41"
pickleshare = "0.7.5"
pilkit = "2.0"
prompt-toolkit = "3.0.26"
ptyprocess = "0.7.0"
Pygments = "2.11.2"
PyJWT = "2.3.0"
python-dateutil = "2.8.2"
pytz = "2021.3"
requests = "2.27.1"
six = "1.16.0"
sqlparse = "0.4.2"
toml = "0.10.2"
traitlets = "5.1.1"
typing-extensions = "4.0.1"
urllib3 = "1.26.8"
wcwidth = "0.2.5"
whitenoise = "5.3.0"
psycopg2 = "^2.8.6"
psycopg2-binary = "^2.8.6"
Pillow = "9.0.0"
Django = "3.2.9"
sentry-sdk = "^1.5.0"
uritemplate = "^4.1.1"
django-mptt = "^0.13.4"
update = "^0.0.1"
boto3 = "1.20.45"
botocore = "^1.23.49"
s3transfer = "^0.5.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = "^21.11b1"
flake8-black = "^0.2.3"
isort = "^5.10.1"
flake8-isort = "^4.1.1"

[tool.black]
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = 'migrations'
safe = true

[tool.isort]
profile = "black"
skip_gitignore = true
skip_glob = "*migrations*"
known_django = ["django", "rest_framework"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
combine_as_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"