[tool.poetry]
name = "aria-api"
version = "0.1.0"
description = ""
authors = ["danielkjellid <daniel.kjellid@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10.2"
appnope = "0.1.2"
backcall = "0.2.0"
boto3 = "1.14.20"
botocore = "1.17.20"
certifi = "2021.10.8"
charset-normalizer = "2.0.7"
confusable_homoglyphs = "3.2.0"
decorator = "5.1.1"
dj-database-url = "0.5.0"
django-appconf = "1.0.4"
django-cors-headers = "3.11.0"
django-environ = "0.8.1"
django-extensions = "^3.1.5"
django-heroku = "0.3.1"
django-imagekit = "4.0.2"
django-s3-storage = "0.13.3"
djangorestframework = "^3.13.1"
djangorestframework-simplejwt = "5.1.0"
docutils = "0.15.2"
gunicorn = "20.1.0"
idna = "3.3"
ipython = "8.2.0"
jedi = "0.18.0"
jmespath = "0.10.0"
matplotlib-inline = "0.1.3"
mypy = "0.910"
mypy-extensions = "0.4.3"
parso = "0.8.2"
pexpect = "4.8.0"
phonenumbers = "8.12.20"
pickleshare = "0.7.5"
pilkit = "2.0"
prompt-toolkit = "3.0.20"
ptyprocess = "0.7.0"
Pygments = "2.11.2"
PyJWT = "2.3.0"
python-dateutil = "2.8.2"
pytz = "2020.1"
requests = "2.26.0"
s3transfer = "0.3.3"
six = "1.16.0"
sqlparse = "0.3.1"
toml = "0.10.2"
traitlets = "5.1.0"
typing-extensions = "4.2.0"
urllib3 = "1.25.9"
wcwidth = "0.2.5"
whitenoise = "5.2.0"
psycopg2 = "^2.8.6"
psycopg2-binary = "^2.8.6"
Pillow = "^9.1.0"
Django = "^3.2.9"
sentry-sdk = "^1.5.0"
uritemplate = "^4.1.1"
django-mptt = "^0.13.4"
pytest-django = "^4.5.2"
pytest-env = "^0.6.2"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-socket = "^0.5.1"
pytest-mock = "^3.7.0"
pytest-lazy-fixture = "^0.6.3"
pytest-remove-stale-bytecode = "^5.0.1"
pytest-xdist = "^2.5.0"
structlog = "^21.5.0"
django-filter = "^21.1"
model-bakery = "^1.5.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = "^22.3"
flake8-black = "^0.2.3"
isort = "^5.10.1"
flake8-isort = "^4.1.1"

[tool.black]
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = 'migrations'
safe = true

[tool.isort]
profile = "black"
skip_gitignore = true
skip_glob = "*migrations*"
known_django = ["django", "rest_framework"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
combine_as_imports = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["aria"]
python_files = "test_*.py"
# Reuse the database between tests
addopts = [
    "--reuse-db",
    "--allow-hosts=localhost,::1,127.0.0.1",
]
# Include captured log messages in system-out in CI report file
junit_logging = "system-out"
# --- pytest-django settings
DJANGO_SETTINGS_MODULE = "aria.settings"
# --- pytest-env settings
env = ["ENV_PATH=.env.test"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"