databases:
  - name: aria
    databaseName: "aria-db-prod"
    user: aria
    region: frankfurt
    postgresMajorVersion: 14

services:
  - type: web
    region: frankfurt
    name: "aria-api-prod"
    env: python
    buildCommand: "./bin/build"
    startCommand: "gunicorn aria.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aria
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: WEB_CONCURRENCY
        value: 4