databases:
  - name: aria-db-prod
    region: frankfurt
    plan: standard
    databaseName: aria
    user: aria
    postgresMajorVersion: 14
  - name: aria-db-staging
    region: frankfurt
    plan: free
    databaseName: aria
    user: aria
    postgresMajorVersion: 14

services:

  ################
  ## Production ##
  ################
  - type: celery
    region: frankfurt
    plan: starter
    name: aria-celery-prod
    env: docker
    dockerCommand: "./docker-entrypoint.sh celery,important,newsletter,misc-tasks"
    envCars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: aria-redis-prod
          property: connectionString

  - type: redis
    region: frankfurt
    plan: starter
    name: aria-redis-prod
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

  - type: web
    region: frankfurt
    plan: Starter Plus
    name: aria-api-prod
    env: docker
    dockerCommand: "./docker-entrypoint.sh gunicorn"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aria-db-prod
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: WEB_CONCURRENCY
        value: 4
      - key: CACHE_URL
        fromService:
          type: redis
          name: aria-redis-prod
          property: connectionString

  #############
  ## Staging ##
  #############
  - type: redis
    region: frankfurt
    plan: free
    name: aria-redis-staging
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

  - type: web
    region: frankfurt
    plan: starter
    name: aria-api-staging
    env: docker
    dockerCommand: "./docker-entrypoint.sh gunicorn"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aria-db-staging
          property: connectionString
      - key: ENVIRONMENT
        value: staging
      - key: WEB_CONCURRENCY
        value: 4
      - key: CACHE_URL
        fromService:
          type: redis
          name: aria-redis-staging
          property: connectionString