databases:
  - name: aria
    databaseName: "aria-db"
    user: aria
    region: frankfurt
    postgresMajorVersion: 14

services:
  - type: web
    region: frankfurt
    name: "aria-api"
    env: python
    buildCommand: "./bin/build"
    startCommand: "gunicorn aria.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aria
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4