# Generated by Django 3.2.11 on 2022-01-25 22:22

import django.db.models.deletion
from django.db import migrations, models

import mptt.fields

import aria.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('image', models.ImageField(blank=True, default='media/front/default_2048x1150.jpeg', upload_to=aria.files.utils.asset_get_static_upload_path, verbose_name='Image')),
                ('apply_filter', models.BooleanField(default=False, help_text='Apply filter to image if the image is light to maintain an acceptable contrast', verbose_name='Apply filter')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='A slug is a short label for something, containing only letters, numbers, underscores or hyphens. They’re generally used in URLs.')),
                ('description', models.TextField(blank=True)),
                ('ordering', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Order  in which the category should be displayed.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the category should be treated as active.')),
                ('promotion_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'New')], default=None, null=True)),
                ('google_taxonomy_id', models.CharField(blank=True, help_text='Used for classification in Google Merchant center. Link to ids: https://www.google.com/basepages/producttype/taxonomy-with-ids.en-US.txt', max_length=50)),
                ('mptt_left', models.PositiveIntegerField(editable=False)),
                ('mptt_right', models.PositiveIntegerField(editable=False)),
                ('mptt_tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
