# Generated by Django 3.2.12 on 2022-05-07 20:02

from django.db import migrations, models

import aria.files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=aria.files.utils.asset_get_static_upload_path, verbose_name='Image'),
        ),
    ]
