# Generated by Django 3.2.12 on 2022-04-27 13:03

from django.db import migrations, transaction
from django.core.files.base import ContentFile


def _update_category_in_bluk(categories, instance):
    for i, category in enumerate(categories):
        if category.slug == instance.slug:
            category.name = instance.name
            category.ordering = instance.ordering
            category.is_active = instance.is_active

            try:
                category.description = instance.description
            except AttributeError:
                pass

            if instance.image and instance.image.name:
                category_image = ContentFile(instance.image.read())
                category_image.name = f"{instance.image.name}_1"

                category.image = category_image

            category.save()


def backfill_updated_data_from_product_categorization(apps, schema_editor):
    product_categorization_category_model = apps.get_model(
        "product_categorization", "Category"
    )
    category_model = apps.get_model("categories", "Category")
    categories = category_model.objects.all()
    with transaction.atomic():
        for product_category in product_categorization_category_model.objects.all():

            _update_category_in_bluk(categories=categories, instance=product_category)

            for subcategory in product_category.children.all():
                _update_category_in_bluk(categories=categories, instance=subcategory)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('categories', '0003_auto_20220126_1700'),
    ]

    operations = [
        migrations.RunPython(
            backfill_updated_data_from_product_categorization, reverse_code=migrations.RunPython.noop
        ),
    ]

