# Generated by Django 4.0.6 on 2022-07-27 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('profile_picture', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/employees/')),
                ('offers_appointments', models.BooleanField(default=False, help_text='Enables appointment booking for employee')),
                ('display_in_team_section', models.BooleanField(default=True, help_text="Display employee under 'Our team' frontend")),
                ('site', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_info', to='sites.site')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_info', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'employee info',
                'verbose_name_plural': 'employee info',
            },
        ),
    ]
