# Generated by Django 3.2.12 on 2022-05-07 20:02

from django.db import migrations, models

import imagekit.models.fields

import aria.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image must be above 380x575px', upload_to=aria.files.utils.asset_get_static_upload_path),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(blank=True, upload_to=aria.files.utils.asset_get_static_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='plywood',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image must be above 380x575px', upload_to=aria.files.utils.asset_get_static_upload_path),
        ),
    ]
