# Generated by Django 4.0.4 on 2022-05-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0002_auto_20220507_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decor',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='plywood',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='decor_variants',
            field=models.ManyToManyField(blank=True, related_name='kitchens', to='kitchens.decor'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='exclusive_variants',
            field=models.ManyToManyField(blank=True, related_name='kitchens', to='kitchens.exclusivecolor'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='laminate_variants',
            field=models.ManyToManyField(blank=True, related_name='kitchens', to='kitchens.laminatecolor'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='plywood_variants',
            field=models.ManyToManyField(blank=True, related_name='kitchens', to='kitchens.plywood'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='silk_variants',
            field=models.ManyToManyField(blank=True, related_name='kitchens', to='kitchens.silkcolor'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='trend_variants',
            field=models.ManyToManyField(blank=True, related_name='kitchens', to='kitchens.trendcolor'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
    ]
