# Generated by Django 3.2.9 on 2021-11-27 15:52

import aria.core.utils
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0002_auto_20211117_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='decor',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image must be above 380x575px', null=True, upload_to=aria.core.utils.get_static_asset_upload_path),
        ),
        migrations.AddField(
            model_name='plywood',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image must be above 380x575px', null=True, upload_to=aria.core.utils.get_static_asset_upload_path),
        ),
        migrations.AlterField(
            model_name='decor',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='t'),
        ),
        migrations.AlterField(
            model_name='plywood',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='t'),
        ),
        migrations.AlterField(
            model_name='plywood',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Kitchen playwood name'),
        ),
    ]
