# Generated by Django 3.2.9 on 2021-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0003_auto_20211127_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='example_from_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
