# Generated by Django 3.2.9 on 2021-11-27 21:02

import aria.core.utils
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0004_alter_kitchen_example_from_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/front/default_380x575.jpeg', help_text='Image must be above 380x575px', null=True, upload_to=aria.core.utils.get_static_asset_upload_path),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(blank=True, default='media/front/default_2048x1150.jpeg', null=True, upload_to=aria.core.utils.get_static_asset_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='plywood',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/front/default_380x575.jpeg', help_text='Image must be above 380x575px', null=True, upload_to=aria.core.utils.get_static_asset_upload_path),
        ),
    ]
