# Generated by Django 3.2.11 on 2022-01-21 12:44

import aria.core.fields
import aria.core.utils
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "color_hex",
                    models.CharField(
                        max_length=7, unique=True, verbose_name="Color code"
                    ),
                ),
            ],
            options={
                "verbose_name": "Color",
                "verbose_name_plural": "Colors",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                (
                    "thumbnail",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        default="media/front/default_380x575.jpeg",
                        help_text="Image must be above 380x575px",
                        upload_to=aria.core.utils.get_static_asset_upload_path,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product name")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Draft"),
                            (2, "Hidden"),
                            (3, "Available"),
                            (4, "Discontinued"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A slug is a short label for something, containing only letters, numbers, underscores or hyphens. They’re generally used in URLs.",
                        max_length=255,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "search_keywords",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Search keywords",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="The short description will be displayed on the top part of the product, above the variant selection",
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                ("new_description", models.TextField(verbose_name="New description")),
                (
                    "unit",
                    models.IntegerField(
                        choices=[(1, "m2"), (2, "stk")], default=1, verbose_name="Unit"
                    ),
                ),
                ("vat_rate", models.FloatField(default=0.25, verbose_name="VAT Rate")),
                (
                    "available_in_special_sizes",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the product comes in sizes out of the ordinary",
                        verbose_name="Available in special sizes",
                    ),
                ),
                (
                    "styles",
                    aria.core.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("classic", "Klassisk"),
                                ("concrete", "Betong"),
                                ("luxurious", "Luksus"),
                                ("marble", "Marmor"),
                                ("natural", "Naturlig"),
                                ("scandinavian", "Skandinavisk"),
                                ("structured", "Strukturert"),
                                ("woodenstructure", "Trestruktur"),
                                ("modern", "Moderne"),
                                ("circular", "Rundt"),
                                ("square", "Firkantet"),
                                ("oval", "Ovalt"),
                                ("mirrorwithlight", "Speil med lys"),
                                ("industrial", "Industriell"),
                            ],
                            max_length=50,
                        ),
                        help_text="Which style the product line represent. Want to add more options? Reach out to Daniel.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "applications",
                    aria.core.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("ceiling", "Tak"),
                                ("floor", "Gulv"),
                                ("table", "Bord"),
                                ("outdoors", "Utendørs"),
                                ("sink", "Vask"),
                                ("walls", "Vegger"),
                            ],
                            max_length=50,
                        ),
                        help_text="Area of product usage. Want to add more options? Reach out to Daniel.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "materials",
                    aria.core.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("ceramic", "Keramikk"),
                                ("metal", "Metall"),
                                ("porcelain", "Porselen"),
                                ("wood", "Tre"),
                                ("oak", "Eik"),
                                ("mdf", "MDF"),
                                ("laminate", "Laminat"),
                                ("teak", "Teak"),
                                ("mirror", "Speil"),
                                ("brushedsteel", "Pusset stål"),
                                ("stainlesssteel", "Rustfritt stål"),
                                ("composite", "Kompositt"),
                            ],
                            max_length=50,
                        ),
                        help_text="Material product is made of. Want to add more options? Reach out to Daniel.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "new_materials",
                    aria.core.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("kompositt", "Kompositt"),
                                ("rustfritt stål", "Rustfritt stål"),
                                ("pusset stål", "Pusset stål"),
                                ("tre", "Tre"),
                                ("laminat", "Laminat"),
                                ("glass", "Glass"),
                                ("marmor", "Marmor"),
                            ],
                            max_length=50,
                        ),
                        help_text="Material product is made of. Want to add more options? Reach out to Daniel.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "rooms",
                    aria.core.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("badrom", "Bad"),
                                ("kjøkken", "Kjøkken"),
                                ("stue gang oppholdsrom", "Stue, gang og oppholdsrom"),
                                ("uterom", "Uterom"),
                            ],
                            max_length=50,
                        ),
                        help_text="Rooms applicable to product.",
                        null=True,
                        size=None,
                    ),
                ),
                ("absorption", models.FloatField(blank=True, null=True)),
                (
                    "is_imported_from_external_source",
                    models.BooleanField(default=False),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "permissions": (
                    ("has_products_list", "Can list products"),
                    ("has_product_edit", "Can edit a single product instance"),
                    ("has_product_add", "Can add a single product instance"),
                    ("has_product_delete", "Can delete a single product instance"),
                ),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProductFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=aria.core.utils.get_static_asset_upload_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Product file name"),
                ),
            ],
            options={
                "verbose_name": "Product file",
                "verbose_name_plural": "Product files",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="media/front/default_2048x1150.jpeg",
                        upload_to=aria.core.utils.get_static_asset_upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "apply_filter",
                    models.BooleanField(
                        default=False,
                        help_text="Apply filter to image if the image is light to maintain an acceptable contrast",
                        verbose_name="Apply filter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                (
                    "gross_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Draft"),
                            (2, "Hidden"),
                            (3, "Available"),
                            (4, "Discontinued"),
                        ],
                        default=3,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product option",
                "verbose_name_plural": "Product options",
            },
        ),
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="media/front/default_2048x1150.jpeg",
                        upload_to=aria.core.utils.get_static_asset_upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Shape",
                "verbose_name_plural": "Shapes",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="width in centimeters",
                        max_digits=6,
                        null=True,
                        verbose_name="width",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="height in centimeters",
                        max_digits=6,
                        null=True,
                        verbose_name="height",
                    ),
                ),
                (
                    "depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="depth in centimeters",
                        max_digits=6,
                        null=True,
                        verbose_name="depth",
                    ),
                ),
                (
                    "circumference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="circumference in centimeters",
                        max_digits=6,
                        null=True,
                        verbose_name="circumference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Size",
                "verbose_name_plural": "Sizes",
                "ordering": ["width", "height", "depth", "circumference"],
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        default="media/front/default_380x575.jpeg",
                        help_text="Image must be above 380x575px",
                        upload_to=aria.core.utils.get_static_asset_upload_path,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Product variant name"
                    ),
                ),
                (
                    "is_standard",
                    models.BooleanField(
                        default=False,
                        help_text="designates if a variant should be treated as standard. This is to avoid multiple instances of the same variant. This field will also prevent cleanup deletion of these models.",
                        verbose_name="standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant",
                "verbose_name_plural": "Variants",
            },
        ),
        migrations.AddConstraint(
            model_name="size",
            constraint=models.UniqueConstraint(
                fields=("width", "height", "depth", "circumference"),
                name="size_combo_unique",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_options",
                to="products.size",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_options",
                to="products.variant",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productfile",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products", to="product_categorization.SubCategory"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(related_name="products", to="products.Color"),
        ),
        migrations.AddField(
            model_name="product",
            name="shapes",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.Shape"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddConstraint(
            model_name="productoption",
            constraint=models.UniqueConstraint(
                fields=("product", "variant", "size"),
                name="one_option_combo_per_variant_size",
            ),
        ),
    ]
