# Generated by Django 3.2.11 on 2022-01-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_new_materials'),
        ('products', '0002_auto_20220121_1408'),
    ]

    operations = [
    ]
