# Generated by Django 3.0.7 on 2021-10-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211025_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='product',
            name='styles',
        ),
        migrations.DeleteModel(
            name='ProductApplication',
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
        migrations.DeleteModel(
            name='ProductStyle',
        ),
    ]
