# Generated by Django 3.0.7 on 2021-10-26 18:56

import aria.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211026_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='temp_applications',
            new_name='applications',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='temp_materials',
            new_name='materials',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='temp_styles',
            new_name='styles',
        ),
    ]
