# Generated by Django 3.2.11 on 2022-01-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20220125_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='product',
            name='styles',
        ),
    ]
