# Generated by Django 3.2.11 on 2022-01-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220125_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_materials',
            new_name='materials',
        ),
    ]
