# Generated by Django 4.0.6 on 2022-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_materials_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sites',
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_picked_up',
            field=models.BooleanField(default=False, help_text='Designates whether the product can be purchased and picked up in store', verbose_name='can be picked up'),
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_purchased_online',
            field=models.BooleanField(default=False, help_text='Designates whether the product can be purchased and shipped', verbose_name='can be purchased online'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_price',
            field=models.BooleanField(default=True, help_text='Designates whether the product price is displayed', verbose_name='display price to customer'),
        ),
        migrations.DeleteModel(
            name='ProductSiteState',
        ),
    ]
