# Generated by Django 4.1 on 2022-08-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0001_squashed_0008_remove_product_sites_product_can_be_picked_up_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description",
        ),
    ]
