# Generated by Django 4.1 on 2022-08-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_remove_product_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="new_description",
            new_name="description",
        ),
    ]
