# Generated by Django 3.0.7 on 2021-11-15 20:01

import aria.core.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211112_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image must be above 380x575px', null=True, upload_to=aria.core.utils.get_static_asset_upload_path),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image must be above 380x575px', null=True, upload_to=aria.core.utils.get_static_asset_upload_path),
        ),
        migrations.AlterField(
            model_name='variant',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image must be above 380x575px', null=True, upload_to=aria.core.utils.get_static_asset_upload_path),
        ),
    ]
