# Generated by Django 4.1.1 on 2022-10-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_rename_new_description_product_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    (
                        "product.view",
                        "Has access to view limited info about a product.",
                    ),
                    (
                        "product.management",
                        "Has access to manage products (add, edit, etc).",
                    ),
                    (
                        "product.admin",
                        "Has admin access to all product functionality, including all info.",
                    ),
                ],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
    ]
