# Generated by Django 4.1.1 on 2022-10-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_attributes", "0001_initial"),
        ("products", "0011_alter_product_options_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoption",
            name="size_attr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_options",
                to="product_attributes.size",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="variant_attr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_options",
                to="product_attributes.variant",
            ),
        ),
    ]
