# Generated by Django 3.0.7 on 2021-11-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211115_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
