# Generated by Django 4.1.1 on 2022-10-22 14:46

from django.db import migrations, models
from django.db.migrations.operations import RunPython


def backfill_shape_relations(apps, schema_editor):
    """
    Populate shapes from product_attributes instead of products.
    """

    Product = apps.get_model("products", "Product")
    Shape = apps.get_model("product_attributes", "Shape")

    for product in Product.objects.all():
        product_shape_ids = product.shapes.all().values_list("id", flat=True)
        shapes = Shape.objects.filter(id__in=product_shape_ids)

        product.shapes_attr.set(list(shapes))


def backfill_color_relations(apps, schema_editor):
    """
    Populate colors from product_attributes instead of products.
    """

    Product = apps.get_model("products", "Product")
    Color = apps.get_model("product_attributes", "Color")

    for product in Product.objects.all():
        product_color_ids = product.colors.all().values_list("id", flat=True)
        colors = Color.objects.filter(id__in=product_color_ids)

        product.colors_attr.set(list(colors))


class Migration(migrations.Migration):

    atomic = True

    dependencies = [
        ("product_attributes", "0002_auto_20221022_1517"),
        ("products", "0012_productoption_size_attr_productoption_variant_attr"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="colors_attr",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="product_attributes.color"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shapes_attr",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="product_attributes.shape"
            ),
        ),
        RunPython(backfill_color_relations, RunPython.noop),
        RunPython(backfill_shape_relations, RunPython.noop),
        migrations.RemoveField(
            model_name="productoption",
            name="size",
        ),
        migrations.RemoveField(
            model_name="productoption",
            name="variant",
        ),
        migrations.RenameField(
            model_name="productoption",
            old_name="variant_attr",
            new_name="variant"
        ),
        migrations.RenameField(
            model_name="productoption",
            old_name="size_attr",
            new_name="size"
        ),
    ]
