# Generated by Django 4.1.1 on 2022-10-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_remove_productoption_size_attr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Size",
        ),
        migrations.DeleteModel(
            name="Variant",
        ),
        migrations.RemoveField(
            model_name="product",
            name="colors",
        ),
        migrations.RemoveField(
            model_name="product",
            name="shapes",
        ),
        migrations.DeleteModel(
            name="Color",
        ),
        migrations.DeleteModel(
            name="Shape",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="shapes_attr",
            new_name="shapes"
        ),
        migrations.RenameField(
            model_name="product",
            old_name="colors_attr",
            new_name="colors"
        ),
    ]
