# Generated by Django 4.1.2 on 2022-11-05 13:31

import aria.files.utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_delete_size_delete_variant_remove_product_colors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_main_image",
            field=models.BooleanField(
                default=False,
                help_text="The image we display first in a series of related images. Should only apply to one of the images in relation.",
                verbose_name="Is main image",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modified time"),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=aria.files.utils.asset_get_static_upload_path,
                verbose_name="thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="file",
            field=models.FileField(
                upload_to=aria.files.utils.asset_get_static_upload_path,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=aria.files.utils.asset_get_static_upload_path,
                verbose_name="Image",
            ),
        ),
    ]
