# Generated by Django 4.1.2 on 2022-12-05 14:35

import aria.files.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_delete_size_delete_variant_remove_product_colors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2022, 12, 5, 14, 35, 13, 906791, tzinfo=datetime.timezone.utc
                ),
                verbose_name="created time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_main_image",
            field=models.BooleanField(
                default=False,
                help_text="The image we display first in a series of related images. Should only apply to one of the images in relation.",
                verbose_name="Is main image",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modified time"),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=aria.files.utils.asset_get_static_upload_path,
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=aria.files.utils.asset_get_static_upload_path,
                verbose_name="Image",
            ),
        ),
    ]
