# Generated by Django 4.1.2 on 2022-11-04 15:01

import aria.files.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0015_productimage_created_at_productimage_is_main_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=aria.files.utils.asset_get_static_upload_path,
                verbose_name="Image",
            ),
        ),
    ]
