# Generated by Django 4.1.3 on 2023-01-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_attributes", "0004_material_room"),
        (
            "products",
            "0015_productimage_created_at_productimage_is_main_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new_materials",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="product_attributes.material"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="new_rooms",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="product_attributes.room"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                help_text="A slug is a short label for something, containing only letters, numbers, underscores or hyphens. They’re generally used in URLs.",
                max_length=255,
                verbose_name="slug",
            ),
        ),
    ]
