# Generated by Django 4.1.3 on 2023-01-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_product_new_materials_product_new_rooms_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="materials",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rooms",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="new_materials",
            new_name="materials",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="new_rooms",
            new_name="rooms",
        ),
    ]
