# Generated by Django 3.2.9 on 2021-12-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20211214_2135'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='size',
            name='one_height_width_combo',
        ),
        migrations.RemoveConstraint(
            model_name='size',
            name='one_height_width_depth_combo',
        ),
    ]
