# Generated by Django 3.2.9 on 2021-12-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_size_size_combo_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='designates if a variant should be treated as standard. This is to avoid multiple instances of the same variant. This field will also prevent cleanup deletion of these models.', verbose_name='standard'),
        ),
    ]
