# Generated by Django 3.2.9 on 2021-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='status',
        ),
        migrations.AddField(
            model_name='productoption',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Hidden'), (3, 'Available'), (4, 'Discontinued')], default=3, verbose_name='Status'),
        ),
    ]
