# Generated by Django 3.2.9 on 2022-01-17 17:38

import aria.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_product_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='new_description',
            field=models.TextField(default='New', verbose_name='New description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='new_materials',
            field=aria.core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('kompositt', 'Kompositt'), ('rustfritt stål', 'Rustfritt stål'), ('pusset stål', 'Pusset stål'), ('tre', 'Tre'), ('laminat', 'Laminat'), ('glass', 'Glass'), ('marmor', 'Marmor')], max_length=50), help_text='Material product is made of. Want to add more options? Reach out to Daniel.', null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='rooms',
            field=aria.core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('badrom', 'Bad'), ('kjøkken', 'Kjøkken'), ('stue gang oppholdsrom', 'Stue, gang og oppholdsrom'), ('uterom', 'Uterom')], max_length=50), help_text='Material product is made of. Want to add more options? Reach out to Daniel.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='shapes',
            field=models.ManyToManyField(related_name='products', to='products.Shape'),
        ),
    ]
