# Generated by Django 3.2.9 on 2022-01-18 20:30

import aria.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20220117_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rooms',
            field=aria.core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('badrom', 'Bad'), ('kjøkken', 'Kjøkken'), ('stue gang oppholdsrom', 'Stue, gang og oppholdsrom'), ('uterom', 'Uterom')], max_length=50), help_text='Rooms applicable to product.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='shapes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Shape'),
        ),
    ]
