# Generated by Django 4.1.2 on 2022-11-08 09:45

import aria.files.utils
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("product_attributes", "0002_auto_20221022_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shape",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=aria.files.utils.asset_get_static_upload_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[350, 575],
                upload_to=aria.files.utils.asset_get_static_upload_path,
                verbose_name="thumbnail",
            ),
        ),
    ]
