# Generated by Django 3.0.7 on 2020-10-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/products', verbose_name='Image'),
        ),
    ]
