# Generated by Django 3.0.7 on 2020-10-01 12:52

from django.db import migrations, models
import imagekit.models.fields
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201001_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfiles',
            options={'verbose_name': 'Product file', 'verbose_name_plural': 'Product files'},
        ),
        migrations.AddField(
            model_name='productfiles',
            name='available_for_download',
            field=models.BooleanField(default=True, verbose_name='Available for download'),
        ),
        migrations.AlterField(
            model_name='productfiles',
            name='upload',
            field=models.FileField(upload_to='media/products/name/files/filename', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/name/images/filename', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/products/name/variants/filename'),
        ),
    ]
