# Generated by Django 3.0.7 on 2020-10-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20201001_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFiles',
            new_name='ProductFile',
        ),
    ]
