# Generated by Django 3.0.7 on 2020-10-02 21:32

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20201002_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image, should only be used on top level parents!', null=True, upload_to='some/category/image/path', verbose_name='Image'),
        ),
    ]
