# Generated by Django 3.0.7 on 2020-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20201011_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Search keywords'),
        ),
    ]
