# Generated by Django 3.0.7 on 2020-10-28 22:21

from django.db import migrations, models
import inventory.models.kitchen


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20201022_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='category',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='extra_description',
            field=models.TextField(blank=True, help_text='Will be displayed bellow pricing example', null=True, verbose_name='Extra description'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(blank=True, help_text='Image must be above 3072x940px', null=True, upload_to=inventory.models.kitchen.Kitchen.kitchen_directory_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='thumbnail_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thumbnail description'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Image must be above 850x520px', null=True, upload_to='media/kitchens/thumbnails/filename', verbose_name='Thumbnail'),
        ),
        migrations.DeleteModel(
            name='KitchenImage',
        ),
    ]
