# Generated by Django 3.0.7 on 2020-10-28 22:33

from django.db import migrations, models
import django.db.models.deletion
import inventory.models.kitchen


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20201028_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_price', models.FloatField(verbose_name='From price')),
                ('image', models.ImageField(blank=True, help_text='Image must be above 3072x940px', null=True, upload_to=inventory.models.kitchen.KitchenExample.kitchen_example_directory_path, verbose_name='Image')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kithcen_example', to='inventory.Kitchen')),
            ],
        ),
    ]
