# Generated by Django 3.0.7 on 2020-10-28 22:34

from django.db import migrations, models
import inventory.models.kitchen


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20201028_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenexample',
            name='image',
            field=models.ImageField(blank=True, help_text='Image must be above 550x300px', null=True, upload_to=inventory.models.kitchen.KitchenExample.kitchen_example_directory_path, verbose_name='Image'),
        ),
    ]
