# Generated by Django 3.0.7 on 2020-10-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20201028_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitchentrendcolor',
            options={'verbose_name': 'Kithcen trend color', 'verbose_name_plural': 'Kitchen trend colors'},
        ),
    ]
