# Generated by Django 3.0.7 on 2020-10-28 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_kitchen_search_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenexample',
            name='kitchen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_example', to='inventory.Kitchen'),
        ),
    ]
