# Generated by Django 3.0.7 on 2020-10-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20201029_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitchenplywood',
            options={'verbose_name': 'Kithcen plywood', 'verbose_name_plural': 'Kitchen plywoods'},
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='thumbnail_description',
            field=models.CharField(default='test', max_length=255, verbose_name='Thumbnail description'),
            preserve_default=False,
        ),
    ]
