# Generated by Django 3.0.7 on 2020-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20201029_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='example_from_price',
            field=models.FloatField(blank=True, null=True, verbose_name='From price'),
        ),
        migrations.DeleteModel(
            name='KitchenExample',
        ),
    ]
