# Generated by Django 3.0.7 on 2020-11-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20201029_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_purchase_price',
            field=models.FloatField(default=0.0, verbose_name='Supplier purchase price'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_discount',
            field=models.FloatField(blank=True, help_text='Supplier discount in percent. E.g. 0.2 = 20%', null=True),
        ),
    ]
