# Generated by Django 3.0.7 on 2020-11-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20201127_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_shipping_cost',
            field=models.FloatField(default=0.0, verbose_name='Shipping cost'),
        ),
    ]
