# Generated by Django 3.0.7 on 2020-11-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_product_supplier_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='product_size_old', to='inventory.ProductSize'),
        ),
        migrations.RenameModel(
            old_name='ProductSize',
            new_name='Size',
        ),
        migrations.CreateModel(
            name='ProductVariantSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_cost', models.FloatField(verbose_name='Additional cost')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='inventory.Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='inventory.Size')),
            ],
            options={
                'verbose_name': 'Product size',
                'verbose_name_plural': 'Product size',
            },
        ),
    ]
