# Generated by Django 3.0.7 on 2020-11-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20201129_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantsize',
            options={'verbose_name': 'Product size', 'verbose_name_plural': 'Product sizes'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='size',
            name='circumference',
            field=models.IntegerField(blank=True, help_text='circumference in centimeters', null=True, verbose_name='Circumference'),
        ),
        migrations.AlterField(
            model_name='size',
            name='height',
            field=models.IntegerField(blank=True, help_text='height in centimeters', null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.IntegerField(blank=True, help_text='width in centimeters', null=True, verbose_name='Width'),
        ),
    ]
