# Generated by Django 3.0.7 on 2020-11-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20201129_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='inventory.Size'),
        ),
    ]
