# Generated by Django 3.0.7 on 2021-01-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20201129_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['width'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
    ]
