# Generated by Django 3.0.7 on 2021-02-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20210122_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['width', 'height', 'depth', 'circumference'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
    ]
