# Generated by Django 3.0.7 on 2021-03-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('inventory', '0036_auto_20210318_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='product_site', to='sites.Site'),
        ),
    ]
