# Generated by Django 3.0.7 on 2021-03-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_auto_20210320_1513'),
    ]

    database_operations = [
        migrations.AlterModelTable('KitchenSilkColor', 'kitchens_kitchensilkcolor'),
        migrations.AlterModelTable('KitchenDecor', 'kitchens_kitchendecor'),
        migrations.AlterModelTable('KitchenPlywood', 'kitchens_kitchenplywood'),
        migrations.AlterModelTable('KitchenLaminateColor', 'kitchens_kitchenlaminatecolor'),
        migrations.AlterModelTable('KitchenExclusiveColor', 'kitchens_kitchenexclusivecolor'),
        migrations.AlterModelTable('KitchenTrendColor', 'kitchens_kitchentrendcolor'),
        migrations.AlterModelTable('Kitchen', 'kitchens_kitchen'),
    ]

    state_operations = [
        migrations.DeleteModel('KitchenSilkColor'),
        migrations.DeleteModel('KitchenDecor'),
        migrations.DeleteModel('KitchenPlywood'),
        migrations.DeleteModel('KitchenLaminateColor'),
        migrations.DeleteModel('KitchenExclusiveColor'),
        migrations.DeleteModel('KitchenTrendColor'),
        migrations.DeleteModel('Kitchen'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
