# Generated by Django 3.0.7 on 2021-05-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_auto_20210324_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='apply_filter',
            field=models.BooleanField(default=False, help_text='Apply filter to image if the image is light to maintain an acceptable contrast', verbose_name='Apply filter'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='apply_filter',
            field=models.BooleanField(default=False, help_text='Apply filter to image if the image is light to maintain an acceptable contrast', verbose_name='Apply filter'),
        ),
    ]
