# Generated by Django 3.0.7 on 2021-05-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('inventory', '0041_auto_20210529_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSiteState',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.Product')),
                ('gross_price', models.FloatField(verbose_name='Gross price')),
                ('supplier_purchase_price', models.FloatField(default=0.0, verbose_name='Supplier purchase price')),
                ('supplier_shipping_cost', models.FloatField(default=0.0, verbose_name='Shipping cost')),
                ('sites', models.ManyToManyField(blank=True, related_name='product_site_state', to='sites.Site')),
            ],
        ),
    ]
