# Generated by Django 3.0.7 on 2021-05-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('inventory', '0043_delete_productsitestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_price',
            field=models.ManyToManyField(blank=True, related_name='display_price_product_site', to='sites.Site'),
        ),
    ]
