# Generated by Django 3.0.7 on 2021-05-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('inventory', '0044_product_display_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSiteState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_price', models.FloatField(verbose_name='Gross price')),
                ('supplier_purchase_price', models.FloatField(default=0.0, verbose_name='Supplier purchase price')),
                ('supplier_shipping_cost', models.FloatField(default=0.0, verbose_name='Shipping cost')),
                ('display_price', models.ManyToManyField(blank=True, related_name='display_price_site', to='sites.Site')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_state', to='inventory.Product')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
