# Generated by Django 3.0.7 on 2021-05-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_productsitestate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsitestate',
            name='display_price',
        ),
        migrations.AddField(
            model_name='productsitestate',
            name='display_price',
            field=models.BooleanField(default=True, help_text='Designates whether the product price is displayed', verbose_name='Display price to customer'),
        ),
    ]
