# Generated by Django 3.0.7 on 2021-05-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_auto_20210530_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='can_be_picked_up',
        ),
        migrations.RemoveField(
            model_name='product',
            name='can_be_purchased_online',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gross_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_shipping_cost',
        ),
    ]
