# Generated by Django 3.0.7 on 2021-10-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_auto_20210530_1814'),
    ]

    database_operations = [
        migrations.AlterModelTable('ProductColor', 'products_productcolor'),
        migrations.AlterModelTable('ProductStyle', 'products_productstyle'),
        migrations.AlterModelTable('ProductApplication', 'products_productapplication'),
        migrations.AlterModelTable('ProductMaterial', 'products_productmaterial'),
        migrations.AlterModelTable('Product', 'products_product'),
        migrations.AlterModelTable('ProductSiteState', 'products_productsitestate'),
        migrations.AlterModelTable('ProductImage', 'products_productimage'),
        migrations.AlterModelTable('ProductVariant', 'products_productvariant'),
        migrations.AlterModelTable('ProductVariantSize', 'products_productvariantsize'),
        migrations.AlterModelTable('ProductFile', 'products_productfile')
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsitestate',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsitestate',
            name='site',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariantsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariantsize',
            name='size',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductApplication',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductFile',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
        migrations.DeleteModel(
            name='ProductSiteState',
        ),
        migrations.DeleteModel(
            name='ProductStyle',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='ProductVariantSize',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
