# Generated by Django 3.0.7 on 2021-10-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_auto_20211017_1607'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='sites',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )
    ]
