# Generated by Django 3.0.7 on 2021-10-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211017_1725'),
        ('kitchens', '0005_auto_20211017_1725'),
        ('inventory', '0052_remove_supplier_sites'),
    ]

    database_operations = [
        migrations.AlterModelTable('Supplier', 'suppliers_supplier')
    ]

    state_operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
