# Generated by Django 3.0.7 on 2021-10-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211017_1725'),
        ('inventory', '0053_delete_supplier'),
    ]

    database_operations = [
        migrations.AlterModelTable('Category', 'product_categorization_category'),
        migrations.AlterModelTable('SubCategory', 'product_categorization_subcategory')
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='sites',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(database_operations=database_operations, state_operations=state_operations)
    ]
