# Generated by Django 4.0.6 on 2022-08-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sitemessage',
            name='site',
        ),
    ]
