# Generated by Django 4.0.5 on 2022-06-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'verbose_name': 'Opening hours', 'verbose_name_plural': 'Opening hours'},
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='openinghourstimeslot',
            name='opening_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='front.openinghours'),
        ),
    ]
