# Generated by Django 4.0.5 on 2022-06-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_openinghourstimeslot_close_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghourstimeslot',
            name='weekday',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=50),
        ),
    ]
