# Generated by Django 4.0.5 on 2022-06-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_remove_openinghoursdeviation_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghourstimeslot',
            name='opening_hours_deviations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='front.openinghoursdeviation'),
        ),
    ]
