# Generated by Django 4.0.5 on 2022-06-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_openinghourstimeslot_opening_hours_deviations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openinghourstimeslot',
            old_name='close_at',
            new_name='closing_at',
        ),
        migrations.RenameField(
            model_name='openinghourstimeslot',
            old_name='open_at',
            new_name='opening_at',
        ),
    ]
