# Generated by Django 4.0.5 on 2022-06-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_alter_openinghourstimeslot_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openinghourstimeslot',
            old_name='opening_hours_deviations',
            new_name='opening_hours_deviation',
        ),
    ]
