# Generated by Django 3.0.7 on 2021-11-17 17:32

import aria.core.utils
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product_categorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 17, 17, 32, 5, 26349, tzinfo=utc), verbose_name='created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=aria.core.utils.get_static_asset_upload_path, verbose_name='Image'),
        ),
    ]
