# Generated by Django 3.2.9 on 2021-11-27 21:02

import aria.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categorization', '0002_auto_20211117_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='media/front/default_2048x1150.jpeg', null=True, upload_to=aria.core.utils.get_static_asset_upload_path, verbose_name='Image'),
        ),
    ]
