# Generated by Django 3.2.12 on 2022-05-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_categorization', '0003_subcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='sites',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
