# Generated by Django 3.2.11 on 2022-01-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_categorization', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='subcategory',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='sites',
        ),
    ]
