# Generated by Django 3.2.11 on 2022-01-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteentry',
            options={'permissions': (('has_notes_list', 'Can view notes'), ('has_notes_add', 'Can add new notes'), ('has_note_edit', 'Can edit a single note instance'), ('has_note_delete', 'Can delete a single note instance')), 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
