# Generated by Django 4.0.4 on 2022-05-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_noteentry_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteentry',
            old_name='user',
            new_name='author',
        ),
    ]
