# Generated by Django 4.0.4 on 2022-05-24 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notes', '0003_rename_user_noteentry_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteentry',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteentry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='noteentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='noteentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
    ]
