# Generated by Django 3.2.12 on 2022-04-13 11:35

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='acquisition_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='allow_personalization',
            field=models.BooleanField(default=True, help_text='Decides if a user accepts a personalized experience within the app.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='allow_third_party_personalization',
            field=models.BooleanField(default=True, help_text='Decides if we share user cookies with external sources such as Facebook. This will make the user see adverts and other related content to the app.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(choices=[('#F87171', 'Red'), ('#FBBF24', 'Yellow'), ('#34D399', 'Green'), ('#60A5FA', 'Blue'), ('#A78BFA', 'Purple'), ('#F472B6', 'Pink')], max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='disabled_emails',
            field=models.BooleanField(default=False, help_text='Decides if a user receives email from us. Typically used if we do not want a user to receive marketing (competetors).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts if you want to preserve the data.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether the user is automatically granted all permissions.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_to_newsletter',
            field=models.BooleanField(default=True, help_text='Decides if a user receives marketing emails from us.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'site')},
        ),
    ]
