# Generated by Django 3.2.9 on 2021-11-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210324_2355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="site",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="sites.site"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("email", "site")},
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("email", "site"), name="email_site_unique_user"
            ),
        ),
    ]
