# Generated by Django 3.2.11 on 2022-01-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acquisition_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='acquisition source'),
        ),
    ]
