# Generated by Django 3.0.7 on 2021-10-17 15:25

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    state_operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Supplier name"
                    ),
                ),
                (
                    "contact_first_name",
                    models.CharField(max_length=255, verbose_name="Contact first name"),
                ),
                (
                    "contact_last_name",
                    models.CharField(max_length=255, verbose_name="Contact last name"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        max_length=254, verbose_name="Contact email address"
                    ),
                ),
                (
                    "supplier_discount",
                    models.FloatField(
                        blank=True,
                        help_text="Supplier discount in percent. E.g. 0.2 = 20%",
                        null=True,
                    ),
                ),
                (
                    "origin_country",
                    models.CharField(max_length=255, verbose_name="Origin country"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether the category should be treated as active.",
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier",
                "verbose_name_plural": "suppliers",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
