# Generated by Django 3.2.11 on 2022-01-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='supplier',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='sites',
        ),
    ]
