# Generated by Django 3.2.9 on 2022-02-25 21:13

import aria.core.utils
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 25, 21, 13, 19, 459286, tzinfo=utc), verbose_name='created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, default='media/front/default_2048x1150.jpeg', upload_to=aria.core.utils.get_static_asset_upload_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website_link',
            field=models.CharField(default='https://example.com', max_length=255),
            preserve_default=False,
        ),
    ]
