# Generated by Django 4.0.1 on 2022-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20220121_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='contact email address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_first_name',
            field=models.CharField(max_length=255, verbose_name='contact first name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_last_name',
            field=models.CharField(max_length=255, verbose_name='contact last name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the category should be treated as active.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='supplier name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='origin_country',
            field=models.CharField(max_length=255, verbose_name='origin country'),
        ),
    ]
