# Generated by Django 3.2.11 on 2022-01-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_auto_20211023_1758'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='supplier',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='sites',
        ),
    ]
