# Generated by Django 4.0.4 on 2022-05-31 19:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='origin_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
