# Generated by Django 4.0.6 on 2022-08-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_supplier_origin_country'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='supplier',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='sites',
        ),
    ]
