# Generated by Django 4.1.2 on 2022-12-05 14:35

import aria.files.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0006_alter_supplier_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=aria.files.utils.asset_get_static_upload_path,
                verbose_name="Image",
            ),
        ),
    ]
