# Generated by Django 3.0.7 on 2021-02-14 21:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='change',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
