# Generated by Django 3.0.7 on 2021-03-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20210305_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': (('has_notes_add', 'Can add new notes'), ('has_note_edit', 'Can edit a single note instance'), ('has_note_delete', 'Can delete a single note instance')), 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
