# Generated by Django 3.0.7 on 2021-10-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20210305_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
