# Generated by Django 3.0.7 on 2021-10-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_delete_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
