name: CI

on: push

env:
  DJANGO_SETTINGS_MODULE: aria.settings

jobs:
  python-lint:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "black"
            check: black aria --check --config=pyproject.toml
          - name: "mypy"
            check: mypy aria
          - name: "flake8"
            check: flake8 aria
          - name: "isort"
            check: isort -c aria --check-only --diff
          - name: "pylint"
            check: pylint aria  --output-format=parseable --reports=no
    name: ${{ matrix.name }}
    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: 3.10.2
#      - name: Cache pip downloads
#        uses: actions/cache@v3
#        with:
#          path: ~/.cache/pip
#          key: pip-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
#          restore-keys: |
#            pip-${{ runner.os }}-
#      - run: python3 -m venv pip-env
#      - run: source pip-env/bin/activate
#      - run: pip install poetry==1.1.5  poetry-core==1.0.4
#      - name: Cache Python venv
#        id: cache-venv
#        uses: actions/cache@v3
#        with:
#          path: .venv
#          key: venv-${{ runner.os }}-${{ hashFiles('.python-version', 'poetry.lock') }}
#      - run: poetry install
#        # if: steps.cache-venv.outputs.cache-hit != 'true'
#      - run: poetry run ${{ matrix.check }}
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Run ${{ matrix.name }}
        run:  poetry run ${{ matrix.check }}

  python-tests:
    name: tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_DB: aria
          POSTGRES_USER: aria
          POSTGRES_PASSWORD: aria
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.2
      - name: Cache pip downloads
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - run: pip install poetry==1.1.10  poetry-core==1.0.6
      - name: Cache Python venv
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('.python-version', 'poetry.lock') }}
      - run: poetry install
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - name: Run tests
        run: poetry run pytest
        env:
          DATABASE_URL: postgresql://aria:aria@localhost:${{ job.services.postgres.ports[5432] }}/aria
          # PostgreSQL configuration, used by psql
          PGHOST: localhost
          PGUSER: aria
          PGPASSWORD: aria
          PGDATABASE: aria
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          CACHE_URL: redis://localhost:6379/

  python-missing-init:
    name: missing __init__.py files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: check for missing __init__.py files
        uses: ljodal/python-actions/check-for-missing-init@feature/check-for-missing-init
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          paths: aria

  ci-done:
    # Gather job which deploy workflow can wait on.
    name: CI done
    needs:
    - python-lint
    - python-tests
    - python-missing-init
    runs-on: ubuntu-20.04
    steps:
      - run: echo "CI done!"
