name: CI

on: push

env:
  DJANGO_SETTINGS_MODULE: aria.settings


jobs:
  black:
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@main
    with:
      cmd: poetry run black aria --check --config=pyproject.toml

  mypy:
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@main
    with:
      cmd: poetry run mypy aria

  flake8:
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@main
    with:
      cmd: poetry run flake8 aria

  isort:
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@main
    with:
      cmd: poetry run isort -c aria --check-only --diff

  pylint:
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@main
    with:
      cmd: poetry run pylint aria  --output-format=parseable --reports=no

  python-tests: #
    name: python tests
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@main
    with:
      cmd: poetry run pytest
      postgres-db: aria
      postgres-user: aria
      postgres-password: aria
      minio-bucket: dev:download        # AWS_S3_BUCKET_NAME
      minio-user: aria                  # AWS_ACCESS_KEY_ID
      minio-password: ariatestpassword  # AWS_SECRET_ACCESS_KEY
      use-redis: true

  python-missing-init:
    name: missing __init__.py files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: check for missing __init__.py files
        uses: ljodal/python-actions/check-for-missing-init@feature/check-for-missing-init
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          paths: aria

  ci-done:
    # Gather job which deploy workflow can wait on.
    name: CI done
    needs:
    - black
    - mypy
    - flake8
    - isort
    - pylint
    - python-tests
    - python-missing-init
    runs-on: ubuntu-20.04
    steps:
      - run: echo "CI done!"
