---
name: Deploy

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
#      - name: Wait on CI
#        uses: lewagon/wait-on-check-action@v1.1.1
#        with:
#          ref: ${{ github.ref }}
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          wait-interval: 10
#          running-workflow-name: "Deploy"
#          check-regexp: "(CI done|Python tests)"
#          allowed-conclusions: success
      - name: Deploy to staging
        env:
          RENDER_DEPLOY_ENDPOINT: ${{ secrets.RENDER_DEPLOY_ENDPOINT }}
        run: |
          curl -X POST -d {} $RENDER_DEPLOY_ENDPOINT


#jobs:
#  deploy:
#    name: Staging
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Wait for CI
#        uses: lewagon/wait-on-check-action@v1.1.1
#        with:
#          ref: ${{ github.ref }}
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          wait-interval: 10
##          running-workflow-name: "deploy"
##          allowed-conclusions: success
#          check-name: "CI done"
#      - name: Deploy to staging
#        uses: actions/checkout@v3
#        env:
#          RENDER_DEPLOY_ENDPOINT: ${{ secrets.RENDER_DEPLOY_ENDPOINT }}
#        run: |
#          curl -X POST -d {} $RENDER_DEPLOY_ENDPOINT