---
name: Deploy

on:
  workflow_run:
    branches:
      - main
    workflows:
      - CI
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Create build on Render
        env:
          RENDER_DEPLOY_ENDPOINT: ${{ secrets.RENDER_DEPLOY_ENDPOINT }}
        run: |
          curl -X POST -d {} $RENDER_DEPLOY_ENDPOINT