name: Deploy

on:
  push:
    branches:
      - main
      - "change-ci"

jobs:
  deploy:
    uses: danielkjellid/github-actions/.github/workflows/deploy-render.yaml@local-actions
    with:
      environment: staging
    secrets:
      deployEndpoint: ${{ secrets.RENDER_DEPLOY_ENDPOINT }}
