name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: danielkjellid/github-actions/.github/workflows/deploy-render.yaml@dependabot-automerge-action
    with:
      environment: staging
    secrets:
      deployEndpoint: ${{ secrets.RENDER_DEPLOY_ENDPOINT }}
