# Generated by Django 3.0.7 on 2021-10-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categorization', '0001_initial'),
        ('products', '0002_auto_20211017_1725'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='product_categorization.SubCategory'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
