# Generated by Django 3.0.7 on 2021-11-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211101_2155'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productsize',
            name='unique_product_size',
        ),
    ]
