# Generated by Django 3.0.7 on 2021-11-11 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211111_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductColor',
            new_name='Color',
        ),
        migrations.RenameModel(
            old_name='ProductOptions',
            new_name='ProductOption',
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='price',
            new_name='gross_price',
        ),
    ]
