# Generated by Django 3.0.7 on 2021-11-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211111_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductColor',
            new_name='Color',
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
    ]
