# Generated by Django 3.0.7 on 2021-11-20 23:23

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211120_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('ceramic', 'Keramikk'), ('metal', 'Metall'), ('porcelain', 'Porselen'), ('wood', 'Tre'), ('mirror', 'Speil')], max_length=50), help_text='Material product is made of. Want to add more options? Reach out to Daniel.', null=True, size=None),
        ),
    ]
